### PR TITLE
#170 Add initial implementation of Softshrink activation function.

### PR DESCRIPTION
**Pull request by michalharakal**
Tests are still missing

Related to #170

### CODE REVIEW

**Comment by michalharakal** [comment]
@zaleslaw do you have any recommendation on reading or source code about implementing conditions/if-else as operands in TF 1x. What are then the changes in this regard in TF 2.x?

**Comment by zaleslaw** [comment]
So @michalharakal if it's possible I'm using tf.max(tf.min()) composition (like you in your solution)
Also, I've experimented with the tf.swtichCond() with true and false outputs, but fails sometimes with the logic.
In 1.15 TF I did not found enough support for conditions.

**Comment by michalharakal** [comment]
I will continue with tests, actually to see how it works

**Comment by zaleslaw** [comment]
Hi, @michalharakal could you please add tests to your PR from [here ](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/activations/tests/softshrink_test.py)

**Comment by michalharakal** [comment]
@zaleslaw pls give me a few days....

**Comment by zaleslaw** [comment]
Sure @michalharakal just wanted to remind

**Comment by michalharakal** [comment]
@zaleslaw  pls don't merge I've broken git history, I create a new PR soon. The implementation itself should be fine

**Comment by michalharakal** [comment]
@zaleslaw Hi, we have had discussion regarding some documentation or articles regarding  learning about TF's computational graphs. Meanwhile, I've found this one for me to be very useful https://d3lm.medium.com/understand-tensorflow-by-mimicking-its-api-from-scratch-faa55787170d

**Comment by zaleslaw** [comment]
Good article, I've added a link to the reading list

**Pull request closed without merging**
