### PR TITLE
Add LeakyReLU layer

### LINKED ISSUE #53: Add LeakyReLU layer
We are missing some activation layers to support the export of models from Keras fully. One of them is the LeakyReLU layer.

Add an activation layer class, write documentation for it, write a test for it, try, if possible, create a small trainable network with it (in your own GitHub) and attach a link here in the comments.

The layer should be placed [here](https://github.com/JetBrains/KotlinDL/tree/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/activation)

As a reference implementation, the [ReLU activation layer](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/activation/ReLU.kt) could be used, but feel free to improve it!

Also, support for export and import of activation layer in JSON format should be added (see [ModelLoader.kt ](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelLoader.kt) and [ModelSaver.kt](https://github.com/JetBrains/KotlinDL/blob/master/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/inference/keras/ModelSaver.kt))

A detailed description of the activation layer can be found [here](https://keras.io/api/layers/activation_layers/leaky_relu/)

### PR DESCRIPTION
**Pull request by mkaze**
Resolves #53. This PR adds support for LeakyRelu layer.

- [x] Implement layer class
- [x] Add unit tests for layer implementation
- [x] Add support for importing models containing this layer from JSON config files
- [x] Add support for exporting models containing this layer to JSON config files

### CODE REVIEW

**Comment by zaleslaw** [comment]
Hi, please merge with master, and I'll merge this PR soon

**Comment by mkaze** [comment]
@zaleslaw Done!

**Comment by zaleslaw** [comment]
@mkaze resolve conflicts with your own PR please:)

**Comment by mkaze** [comment]
@zaleslaw I just resolved the conflicts.

**Pull request merged**
