### PR TITLE
Move loading out of preprocessing

### LINKED ISSUE #322: Move loading out of preprocessing
It seems that loading functionality should be moved out of preprocessing to the `Dataset` implementations.
1. Loading images is orthogonal to preprocessing. Having a loading stage limits preprocessors functionality, as it prohibits sharing preprocessors between datasets or applying them to images loaded from elsewhere.
2. Knowledge about the source of the images is intrinsic to some of the `Dataset` implementations, specifically `OnFlyImageDataset`. 
3. The code creating dataset implementations already directly accesses loading stage of the provided `Preprocessing` instance.

### PR DESCRIPTION
**Pull request by juliabeliaeva**
Fixes #322

### CODE REVIEW

**Comment by juliabeliaeva** [comment]
I rebased the branch on master, resolved conflicts and fixed the new examples accordingly with the changes in the branch.

**Comment by zaleslaw** [comment]
The following result is obtained from the TC

java.lang.IllegalArgumentException: file not found! datasets/detection/image0.jpg
  at examples.transferlearning.PredictionRunnerKt.getFileFromResource(predictionRunner.kt:33)
  at examples.onnx.objectdetection.ssd.SSDKt.ssd(SSD.kt:43)
  at examples.onnx.objectdetection.ObjectDetectionTestSuite.ssdTest(ObjectDetectionTestSuite.kt:29)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
  at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)

**Comment by juliabeliaeva** [comment]
> The following result is obtained from the TC

Sorry, made a mistake during rebase. I'll fix it.

**Comment by juliabeliaeva** [comment]
Fixed. Iteration was done on the incorrect range here: https://github.com/juliabeliaeva/KotlinDL/blob/6ef7ccd21b3bbf5889067edbeeea79ed884a0744/examples/src/main/kotlin/examples/onnx/objectdetection/ssd/SSD.kt#L42

**Comment by zaleslaw** [comment]
So @juliabeliaeva it looks good for this moment and releases 0.4 but looks like it's not a final version of Dataset API and its relationships with the Preprocessing and probable different Data Source support.

In my humble opinion, if we move from the concept of materialized Datasets to the lazy Data Loaders, we will return to the DSL again.

But I agree, that data loading should be separated from data transformation.

**Pull request merged**
