### PR TITLE
Dsl builder

### PR DESCRIPTION
**Pull request by smallshen**
https://github.com/JetBrains/KotlinDL/issues/133

### CODE REVIEW

**Comment by smallshen** [comment]
api/src/test/kotlin/org/jetbrains/kotlinx/dl/api/extension/dsl/GraphTrainableModelDslTest.kt

**Comment by smallshen** [comment]
https://github.com/JetBrains/KotlinDL/issues/133

**Comment by zaleslaw** [comment]
Hi @smallshen I keep in mind this beautiful PR. Currently, the community works on the internal codebase and Layer API changes, I hope that during 3-6 weeks we could return to the DSL discussions at the top of the new Layer API

**Comment by smallshen** [comment]
Great, in the meantime I will explore some possibilities with Kotlin Script,

**Comment by zaleslaw** [comment]
@smallshen could you please close this PR and create a new one with only DSL changes added without changes related to CI, dependencies, and plugin updates, just DSL updates.

And add additional example with your changes (not refactoring) for Example_3_ToyResNet_describe_and_train.kt 

I hope to include these changes into 0.4 release

**Pull request closed without merging**
