### PR TITLE
converts functions to poroperties where applicable (#29)

### LINKED ISSUE #29: getOptimizerName convert function to property
Convert function to property
`public abstract fun getOptimizerName(): String`
=>
`public abstract val optimizerName: String`
in `Optimimizer.kt`

### PR DESCRIPTION
**Pull request by LostMekka**
Fixes #29.

Changes:
- Optimizer
  - fun getOptimizerName() -> val optimizerName
  - fun isRunningOnGPU() -> val isRunningOnGPU
- Layer
  - fun getParams() -> val paramCount
  - fun hasActivation() -> val hasActivation 
  - fun getWeights() -> fun extractWeights()
- Dense
  - fun getKernelShape() -> val kernelShapeArray
  - fun getBiasShape() -> val biasShapeArray
- Conv2D
  - fun getKernelShape() -> val kernelShapeArray
  - fun getBiasShape() -> val biasShapeArray

### CODE REVIEW

**Comment by LostMekka** [comment]
@zaleslaw I was not sure about the changes in `Dense` and `Conv2D`. There were name collisions with private properties, so I renamed the public ones. I could also rename the private ones instead to keep the API cleaner...

I also chose the name `extractWeights` for now, but this can of course be changed 😃

**Comment by zaleslaw** [comment]
Dear @LostMekka could I advise you to convert extractWeights to property 'weights' with getter, long body of getter could be extracted to the separate function with name 'extractConv2DWeights' for example? 
Will it became cleaner?

**Comment by zaleslaw** [comment]
All previous changes could be merged, but maybe we achieve more for weights getters

**Comment by LostMekka** [comment]
OK, I have converted `extractWeights` to a property as well :)

**Pull request merged**
